package billingapplication;

/*
 * Imports
 */
import java.awt.Color;
import java.util.Calendar;
import java.util.Random;
import java.text.SimpleDateFormat;

/**
 *
 * @author meganl
 */
public class billingGUI extends javax.swing.JFrame {
    /**Define variables**/
    double firstnum;
    double secondnum;
    double result;
    String operations;
    int intOrderNum = 1000;
    double priceWrap = 8.50;
    double priceSalad = 7.25;
    double priceCookie = 2.50;
    double taxRate = 7.5;

    /**
     * Creates new form billingGUI
     */
    public billingGUI() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        deliIcon = new javax.swing.JLabel();
        jLabel_custName = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        jLabel_custPhone = new javax.swing.JLabel();
        custPhone = new javax.swing.JTextField();
        orderTime = new javax.swing.JTextField();
        jLabel_orderTime = new javax.swing.JLabel();
        jLabel_orderDate = new javax.swing.JLabel();
        orderDate = new javax.swing.JTextField();
        jLabel_orderNum = new javax.swing.JLabel();
        orderNumber = new javax.swing.JTextField();
        jLabel_itemType = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_qty = new javax.swing.JLabel();
        jLabel_unitPrice = new javax.swing.JLabel();
        jLabel_subTotal = new javax.swing.JLabel();
        jLabel_sandwich = new javax.swing.JLabel();
        jLabel_salad = new javax.swing.JLabel();
        jLabel_cookie = new javax.swing.JLabel();
        qtyWrap = new javax.swing.JTextField();
        qtySalad = new javax.swing.JTextField();
        qtyCookie = new javax.swing.JTextField();
        unitWrap = new javax.swing.JTextField();
        unitSalad = new javax.swing.JTextField();
        unitCookie = new javax.swing.JTextField();
        subCookie = new javax.swing.JTextField();
        subSalad = new javax.swing.JTextField();
        subWrap = new javax.swing.JTextField();
        jButton_order = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_receipt = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_orderTax = new javax.swing.JLabel();
        orderTax = new javax.swing.JTextField();
        jLabel_orderSubTotal = new javax.swing.JLabel();
        orderSubTotal = new javax.swing.JTextField();
        jLabel_orderNet = new javax.swing.JLabel();
        orderNet = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Receipt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jtxtDisplay = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deliIcon.setBackground(new java.awt.Color(225, 122, 193));
        deliIcon.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        deliIcon.setIcon(new javax.swing.ImageIcon("/home/meganl/Desktop/deliIcon.jpg")); // NOI18N
        deliIcon.setText("Larkins Deli & Treats");

        jLabel_custName.setText("Customer Name:");

        jLabel_custPhone.setText("Customer Phone:");

        custPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custPhoneActionPerformed(evt);
            }
        });

        orderTime.setEditable(false);

        jLabel_orderTime.setText("Order Time:");

        jLabel_orderDate.setText("Order Date:");

        orderDate.setEditable(false);

        jLabel_orderNum.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel_orderNum.setText("Order Number:");

        orderNumber.setEditable(false);
        orderNumber.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N

        jLabel_itemType.setFont(new java.awt.Font("Cantarell", 3, 14)); // NOI18N
        jLabel_itemType.setText("Item Type");

        jLabel_qty.setFont(new java.awt.Font("Cantarell", 3, 14)); // NOI18N
        jLabel_qty.setText("QTY");

        jLabel_unitPrice.setFont(new java.awt.Font("Cantarell", 3, 14)); // NOI18N
        jLabel_unitPrice.setText("Unit Price");

        jLabel_subTotal.setFont(new java.awt.Font("Cantarell", 3, 14)); // NOI18N
        jLabel_subTotal.setText("Sub Total");

        jLabel_sandwich.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_sandwich.setText("Sandwich Wrap");

        jLabel_salad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_salad.setText("Salad");

        jLabel_cookie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_cookie.setText("Cookie");

        qtyWrap.setText("0");

        qtySalad.setText("0");

        qtyCookie.setText("0");

        unitWrap.setEditable(false);

        unitSalad.setEditable(false);

        unitCookie.setEditable(false);

        jButton_order.setText("Order");
        jButton_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_orderActionPerformed(evt);
            }
        });

        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_receipt.setText("Receipt");
        jButton_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_receiptActionPerformed(evt);
            }
        });

        jButton_exit.setBackground(new java.awt.Color(229, 40, 84));
        jButton_exit.setText("Exit");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jLabel_orderTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_orderTax.setText("Tax Paid:");

        orderTax.setEditable(false);

        jLabel_orderSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_orderSubTotal.setText("SubTotal:");

        orderSubTotal.setEditable(false);
        orderSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSubTotalActionPerformed(evt);
            }
        });

        jLabel_orderNet.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel_orderNet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_orderNet.setText("Net Total:");

        orderNet.setEditable(false);
        orderNet.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        orderNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNetActionPerformed(evt);
            }
        });

        jTextArea_Receipt.setEditable(false);
        jTextArea_Receipt.setColumns(20);
        jTextArea_Receipt.setFont(new java.awt.Font("VL Gothic", 0, 18)); // NOI18N
        jTextArea_Receipt.setRows(5);
        jTextArea_Receipt.setText("-- Please click \"Receipt\" to view --");
        jScrollPane1.setViewportView(jTextArea_Receipt);

        jTabbedPane4.addTab("Receipt", jScrollPane1);

        jButton8.setBackground(new java.awt.Color(243, 127, 39));
        jButton8.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(243, 127, 39));
        jButton20.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton20.setText("=");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(150, 150, 150));
        jButton9.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton9.setText("4");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(150, 150, 150));
        jButton10.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton10.setText("5");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jtxtDisplay.setEditable(false);
        jtxtDisplay.setBackground(java.awt.Color.gray);
        jtxtDisplay.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setBorder(null);

        jButton11.setBackground(new java.awt.Color(150, 150, 150));
        jButton11.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton11.setText("6");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(150, 150, 150));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(243, 127, 39));
        jButton12.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(150, 150, 150));
        jButton2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButton2.setText("-/+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(150, 150, 150));
        jButton13.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton13.setText("1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(150, 150, 150));
        jButton3.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton3.setText("%");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(150, 150, 150));
        jButton14.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton14.setText("2");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(243, 127, 39));
        jButton4.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton4.setText("÷");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(150, 150, 150));
        jButton15.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton15.setText("3");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(150, 150, 150));
        jButton5.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton5.setText("7");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(243, 127, 39));
        jButton16.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(150, 150, 150));
        jButton6.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton6.setText("8");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(150, 150, 150));
        jButton17.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton17.setText("0");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(150, 150, 150));
        jButton7.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton7.setText("9");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(150, 150, 150));
        jButton19.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButton19.setText(".");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDisplay)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Calculator", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_orderTax, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orderTax, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_orderSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orderSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_orderNet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(orderNet, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(deliIcon))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel_orderNum, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_custName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_orderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(orderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(qtyCookie, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_salad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(qtySalad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_sandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(qtyWrap, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_itemType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(unitSalad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unitWrap, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_unitPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(unitCookie))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_subTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(subWrap)
                                    .addComponent(subSalad)
                                    .addComponent(subCookie))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(deliIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_custName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_orderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_orderNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_itemType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_unitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_sandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtyWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_salad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtySalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtyCookie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitCookie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subCookie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_orderSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_orderTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_orderNet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>                        

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    }                                            

    private void orderSubTotalActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void orderNetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void custPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {                                              
        custName.setText("");
        custPhone.setText("");
        orderTime.setText("");
        orderDate.setText("");
        orderNumber.setText("");
        qtyWrap.setText("0");
        qtySalad.setText("0");
        qtyCookie.setText("0");
        subWrap.setText("");
        subSalad.setText("");
        subCookie.setText("");
        orderSubTotal.setText("");
        orderTax.setText("");
        orderNet.setText("");
    }                                             

    private void jButton_orderActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //Create unique calendar symbol(name) "timer" and create instance
        //get current time
        Calendar timer = Calendar.getInstance();
        //below line seems unnessesary, and when I removed it things still worked, maybe best practice?
        timer.getTime();
        //Assign time format, set value to orderTime
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        orderTime.setText(tTime.format(timer.getTime()));
        //Assign date format, set value to orderDate
        SimpleDateFormat tDate = new SimpleDateFormat("MMM-dd-yyyy");
        orderDate.setText(tDate.format(timer.getTime()));
        
        //*Set Random orderNumber*//
        Random rand = new Random();
        //* Create random number between 0 and 9998 *//
        int randNum = rand.nextInt(9999);
        //*System.out.println(randNum);
        orderNumber.setText(String.format("%04d",randNum));
        //* Create string strOrderNum and set value as converted randNum.
        
        //*Set building orderNumber*//
        //*WORKING!*//
        //intOrderNum++;
        //orderNumber.setText(Integer.toString(intOrderNum));
        
        //****Order & Calculations****//
        //*Display prices
        unitWrap.setText(String.format("$%.2f",priceWrap));
        unitSalad.setText(String.format("$%.2f",priceSalad));
        unitCookie.setText(String.format("$%.2f",priceCookie));
        //*Get QTY text from fields
        String qtyWrapStr = qtyWrap.getText();
        String qtySaladStr = qtySalad.getText();
        String qtyCookieStr = qtyCookie.getText();
        //*Convert to Int and Calculate
        double subWrapInt = Integer.parseInt(qtyWrapStr) * priceWrap;
        subWrap.setText(String.format("$%.2f",subWrapInt));
        double subSaladInt = Integer.parseInt(qtySaladStr) * priceSalad;
        subSalad.setText(String.format("$%.2f",subSaladInt));
        double subCookieInt = Integer.parseInt(qtyCookieStr) * priceCookie;
        subCookie.setText(String.format("$%.2f",subCookieInt));
        
        //*Calculate orderSubTotal, orderTax, and orderNet
        double orderSubTotalDbl = subWrapInt + subSaladInt + subCookieInt;
        orderSubTotal.setText(String.format("$%.2f",orderSubTotalDbl));
        double orderTaxDbl = orderSubTotalDbl * (taxRate * 0.01);
        orderTax.setText(String.format("$%.2f",orderTaxDbl));
        double orderNetDbl = orderSubTotalDbl + orderTaxDbl;
        orderNet.setText(String.format("$%.2f",orderNetDbl));
        
        
        
    }                                             

    private void jButton_receiptActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String qtyWrapStr = qtyWrap.getText();
        String qtySaladStr = qtySalad.getText();
        String qtyCookieStr = qtyCookie.getText();
        int totalItems = Integer.parseInt(qtyWrapStr) + Integer.parseInt(qtySaladStr) + Integer.parseInt(qtyCookieStr);
        
        jTextArea_Receipt.setText("Larkins Deli & Treats"
                + "\n "
                + "\n "
                + "\nNumber of Wraps \t" + qtyWrapStr
                + "\nNumber of Salads\t" + qtySaladStr
                + "\nNumber of Cookies\t" + qtyCookieStr
                + "\nTotal number of items\t" + Integer.toString(totalItems)
                + "\n "
                + "\nOrder Ref No \t\t" + orderNumber.getText()
                + "\nDate \t\t" + orderDate.getText()
                + "\nTime \t\t" + orderTime.getText()
                + "\n "
                + "\nThanks for Shopping with us!");
    }                                               

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "*";
    }                                        

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String answer;
        secondnum = Double.parseDouble(jtxtDisplay.getText());
        if (operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
    }                                         

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String Enternumber = jtxtDisplay.getText() + jButton9.getText();
        jtxtDisplay.setText(Enternumber);
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton10.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton11.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String Enternumber = jtxtDisplay.getText() + jButton1.getText();
        jtxtDisplay.setText("");
    }                                        

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "-";
    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }                                        

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton13.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "%";
    }                                        

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton14.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "/";
    }                                        

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton15.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String Enternumber = jtxtDisplay.getText() + jButton5.getText();
        jtxtDisplay.setText(Enternumber);
    }                                        

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "+";
    }                                         

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String Enternumber = jtxtDisplay.getText() + jButton6.getText();
        jtxtDisplay.setText(Enternumber);
    }                                        

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton17.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String Enternumber = jtxtDisplay.getText() + jButton7.getText();
        jtxtDisplay.setText(Enternumber);
    }                                        

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String Enternumber = jtxtDisplay.getText() + jButton19.getText();
        jtxtDisplay.setText(Enternumber);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField custName;
    private javax.swing.JTextField custPhone;
    private javax.swing.JLabel deliIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_order;
    private javax.swing.JButton jButton_receipt;
    private javax.swing.JLabel jLabel_cookie;
    private javax.swing.JLabel jLabel_custName;
    private javax.swing.JLabel jLabel_custPhone;
    private javax.swing.JLabel jLabel_itemType;
    private javax.swing.JLabel jLabel_orderDate;
    private javax.swing.JLabel jLabel_orderNet;
    private javax.swing.JLabel jLabel_orderNum;
    private javax.swing.JLabel jLabel_orderSubTotal;
    private javax.swing.JLabel jLabel_orderTax;
    private javax.swing.JLabel jLabel_orderTime;
    private javax.swing.JLabel jLabel_qty;
    private javax.swing.JLabel jLabel_salad;
    private javax.swing.JLabel jLabel_sandwich;
    private javax.swing.JLabel jLabel_subTotal;
    private javax.swing.JLabel jLabel_unitPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea_Receipt;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField orderDate;
    private javax.swing.JTextField orderNet;
    private javax.swing.JTextField orderNumber;
    private javax.swing.JTextField orderSubTotal;
    private javax.swing.JTextField orderTax;
    private javax.swing.JTextField orderTime;
    private javax.swing.JTextField qtyCookie;
    private javax.swing.JTextField qtySalad;
    private javax.swing.JTextField qtyWrap;
    private javax.swing.JTextField subCookie;
    private javax.swing.JTextField subSalad;
    private javax.swing.JTextField subWrap;
    private javax.swing.JTextField unitCookie;
    private javax.swing.JTextField unitSalad;
    private javax.swing.JTextField unitWrap;
    // End of variables declaration                   
}
